### PR TITLE
Remove object-rest-spread as it is unsupported by Edge

### LINKED ISSUE #39: Windows Edge Support
Windows Edge browser doesn't support object rest spread, so:

`{ ...props, x: 'y' }` is unacceptable and will break your site.

`Object.assign` can be used instead.

I'll open a PR in about ten minutes to fix this.

### PR DESCRIPTION
**Pull request by antony**
Fixes #39

### CODE REVIEW

**Comment by 6eDesign** [comment]
Hey @antony thanks for noticing and fixing this.  There's a linting error or two that will need to be fixed before proceeding with this PR.  

Thanks, 
Jonathan

**Comment by 6eDesign** [comment]
Hey @antony - I was thinking about this some more and realized that I've already been "fixing" this by polyfilling `Object.assign` (for older IE versions) and using buble with the option `objectAssign: true`. 

Are you using babel or buble on your projects?   We could make this unnecessary by using Object.assign directly but there are likely other things that will cause compatibility issues if you're not using babel/buble such as async functions (`await tick()`).   I'd be interested in your thoughts on this as a user & dev.   We could document browser compatibility and instructions for transpilers or we could try to make them unnecessary.  I'm conflicted, personally. 

With that said, happy to accept this PR in the interim if you can fix the linting issues.

**Comment by antony** [comment]
@6eDesign I don't like sticking all my code through a preprocessor or using polyfills when there is really only one thing stopping Edge compatibility. It bloats the filesize and adds a level of abstraction / inefficiency.

I think for the small sacrifice that Object.assign is, it's worth allowing your component to be used in the simplest possible way.

**Comment by 6eDesign** [comment]
@antony that's mostly fair but in case you haven't tried it, buble will simply transform the spread operator to Object.assign (so there's no bloat).  Thanks again for the issue and PR!

**Comment by antony** [comment]
Yeah I should probably try Buble - Babel is baffling :)

**Pull request merged**
