### PR TITLE
Added  display, width & text align

### PR DESCRIPTION
**Pull request by Taha-Firoz**
I know this is probably a very stupid solution to my problem but I just couldn't theme your components without having changed the file. I really think if these properties were exposed to begin with it would've really helped me get the theming over with. I would really appreciate it if you could suggest a less invasive solution to my problem.

### CODE REVIEW

**Comment by Taha-Firoz** [comment]
Basically I recently jumped on the front-end of a project I'm working on. I was trying to add more visually appealing and functional components for the date when I came across your component. 

When I'd add the component to the form it wouldn't stretch to the whole width of the column. I tried alot of things but I really couldn't overwrite the styling you were doing internally. All I wanted was the width to be set to 100% so it'd stretch to the width of the column.

Also whatever width I'd have set wouldn't make a difference until I changed the display type to anything other than 'inline-block'. So basically I just exposed those CSS components. I want to add a disable component too so the date picker field can be disabled.

**Comment by 6eDesign** [comment]
Thank you for explaining.  Your solution does fix your issue but I wonder if we can do something a little more generic to allow it to fix future problems as well.  Perhaps we could add a 'style' prop and then concatenate that value with the existing theming properties, for example (in Datepicker.svelte): 
```
<script>
...
  $: wrapperStyle = `
    --button-background-color: ${buttonBackgroundColor};
    --button-border-color: ${buttonBorderColor};
    --button-text-color: ${buttonTextColor};
    --highlight-color: ${highlightColor};
    --day-background-color: ${dayBackgroundColor};
    --day-text-color: ${dayTextColor};
    --day-highlighted-background-color: ${dayHighlightedBackgroundColor};
    --day-highlighted-text-color: ${dayHighlightedTextColor};
    ${style}
  `;
</script>

<div 
  class="datepicker" 
  class:open="{isOpen}" 
  class:closing="{isClosing}"
  style={wrapperStyle}
>```

**Comment by 6eDesign** [comment]
@Taha-Firoz - in case it wasn't obvious, with my suggestion you could then write: 
`<Datepicker style="display: inline-block; text-align: left; ..." />`

**Comment by 6eDesign** [comment]
@Taha-Firoz - I've gone ahead and implemented the code I described above.  Here's an example of it in use: https://svelte.dev/repl/c4f33d74cc0347b1b3fbc80660e8ecc7?version=3.17.1

Please let me know if this update and example doesn't solve your problem fully.  If it does, feel free to close the issue. :)

**Comment by Taha-Firoz** [comment]
> Thank you for explaining. Your solution does fix your issue but I wonder if we can do something a little more generic to allow it to fix future problems as well. Perhaps we could add a 'style' prop and then concatenate that value with the existing theming properties, for example (in Datepicker.svelte):
> 
> ```
> <script>
> ...
>   $: wrapperStyle = `
>     --button-background-color: ${buttonBackgroundColor};
>     --button-border-color: ${buttonBorderColor};
>     --button-text-color: ${buttonTextColor};
>     --highlight-color: ${highlightColor};
>     --day-background-color: ${dayBackgroundColor};
>     --day-text-color: ${dayTextColor};
>     --day-highlighted-background-color: ${dayHighlightedBackgroundColor};
>     --day-highlighted-text-color: ${dayHighlightedTextColor};
>     ${style}
>   `;
> </script>
> 
> <div 
>   class="datepicker" 
>   class:open="{isOpen}" 
>   class:closing="{isClosing}"
>   style={wrapperStyle}
> >```
> ```

I think this might be a perfect solution to the issue, I really hope other svelte component libraries do the same. Styling components would become extremely easy, let me try this, I'll get back to you in a bit.

**Comment by 6eDesign** [comment]
@Taha-Firoz - I've definitely seen some other components take similar approaches.  Some even just spread _all_ props onto the root element of their component which can be useful.  It doesn't fully solve styling issues though since components are often multiple levels deep but it seems to suit this use case well enough.  I'll go ahead and close this for now but feel free to re-open if you have any problems with the implementation of this feature.

**Pull request closed without merging**
