### PR TITLE
add continuous deployment with github actions

### PR DESCRIPTION
**Pull request by antony**
Just generate and add an `NPM_TOKEN` to the project settings.

When you run your `npm run release` task, a build will run and release to npm automatically.

### CODE REVIEW

**Comment by 6eDesign** [comment]
Hey @antony - does this improve upon the existing release process at all?  Currently, when I run this task it publishes automatically via travis-ci.  I'm happy to experiment with github actions instead of travis ci but the main pain point with the current system is that a merged PR does not automatically publish a new version (a manual run of this script is required).

**Comment by antony** [comment]
Ah yeah - I forgot that you had travis. It isn't really an improvement on that per-se. I was just conscious that you hadn't released after the last merge and I wondered if the process could be improved.

Feel free to close this if Travis is working for you - it's literally a 5 second copy paste job from other repos I have :)

**Comment by 6eDesign** [comment]
Hey @antony - I've published a new version that incorporates your recent PR.  I appreciate seeing what CI with gitlab actions would look like.  I'll keep this open for now so I can keep improving the CI/CD of this package at top of mind.  Ideally, I'd like any commit to master to automate the tagging, changelog generation, and publishing of the module.

**Comment by antony** [comment]
FYI github now supports manual workflows so you can automate the deploy workflow from master.

I would however strongly advise against automating tagging. I would suggest the flow I use which is `npm version <increment> && git push --tags` to trigger an automated tag build + release to npm instead.

**Pull request closed without merging**
