### PR TITLE
Svelte 3 Upgrade

### PR DESCRIPTION
**Pull request by antony**
Fixes https://github.com/6eDesign/svelte-calendar/issues/20

This is still probably lacking - and these can probably be done post merge, since I know a few people are waiting on this v3 upgrade:

- [x] Non-svelte test updated
- [x] Fix slide direction
- [x] Documentation moved to v3 syntax
- [x] In-depth testing of all features
- [x] Filenames changed

Please give it a go and feed back.

Btw - I think immediately after this we should look at moving all the data to a store. There would barely be any code left.

### CODE REVIEW

**Comment by 6eDesign** [comment]
Hey @antony - thanks for taking a crack at this!

Took a quick look at this last night.  It looked like the month change animations were a little broken: the month always animated from the same direction regardless of whether incrementing or decrementing.  Should be easy to fix.  I also think we should update the file extensions to .svelte.

Did you use the svelte upgrade tool to convert?

**Comment by antony** [comment]
@6eDesign I think I know why the directions are broken, I was confused by the logic controlling direction, so I've probably messed it up.

I do agree about file extensions, and I meant to do it, but forgot.

I didn't use the upgrade tool no - I just don't think it's going to be able to do the job! I did it all manually.

**Comment by antony** [comment]
Ok - I've done some further testing and fixed the issue with date direction. I'm happy that it's good to merge if you are :)

**Comment by antony** [comment]
@6eDesign any chance you will get to review and merge this soon?

**Comment by 6eDesign** [comment]
Yes, soon.

**Pull request merged**
