### PR TITLE
Add CircleCI config

### LINKED ISSUE #4: Add CI support
- [ ] Run tests
- [ ] Lint
- [ ] Autopublish to npm on tag
- [ ] Badges

### PR DESCRIPTION
**Pull request by antony**
This is identical to the one I use across all my projects.

- I've left out the test step, as there aren't any tests.
- I've left out the lint step as I don't know what your preference is

To make this work, all you need to do is go to circleci.com, authenticate, and click add project. After that, go to settings/contexts in circleci and add your npm token under a variable called NPM_TOKEN. After that, everything will just work automatically - when you push a tag, it will be deployed to npm.

Fixes #4

### CODE REVIEW

**Comment by 6eDesign** [comment]
This looks nice - I'll try and see about getting it merged in this weekend.

**Comment by antony** [comment]
@6eDesign another one from me - just seeing how this feels as a module and noticed that `timeUtils` is the wrong kind of dependency for it to work - I've fixed this.

**Comment by antony** [comment]
Sounds good - I'll start to use the one from npm now then. I've already integrated it into one of my projects, there are a couple of small issues which I'll raise separately, but other than that it works well!

**Comment by antony** [comment]
Closing as per comments in #4

**Pull request closed without merging**
