### PR TITLE
Issue 62 - year selection

### PR DESCRIPTION
**Pull request by northkode**
added in the ability to render out years between start and end and select them to change the year of the calendar.

### CODE REVIEW

**Comment by 6eDesign** [comment]
Thanks for submitting this PR.  I think this is a good start for this use case but maybe we could improve upon it a bit.  The scrolling approach might work but the appearance of the scrollbar on Windows devices is not that great.  I also think the UX might be more consistent if we continued to show the navbar component when entering the year selector.

We might also want to consider making the keyboard controls more contextual (make them do different things based on whether you're in then day, month, or year picker).  Some of this might be a bit easier if we address another issue which involves adding a store for state management.

I also wonder if we could somehow improve the appearance of the navbar month/year targets to clearly indicate that they are actionable/clickable items.

Would you be interested in collaborating on this a bit more to further refine this experience/feature?

**Comment by loversandcode** [comment]
Guys, do you have any progress on this thing? 

It's very useful function

**Comment by silvestrevivo** [comment]
Hi, there is no progress here?

**Comment by Aylay** [comment]
Any news ?

**Comment by nickpoulos** [comment]
Wow yea this is an absolute deal-breaker of a missing feature, how is this possible? 

All this talk about UX improvements but this component is essentially useless for the most basic use case for a date....Birthday. 

By not allowing the user to select a year, they have to scroll through 20 years of months to select a date in the past.  🤦

**Comment by 6eDesign** [comment]
> Wow yea this is an absolute deal-breaker of a missing feature, how is this possible?
> 
> All this talk about UX improvements but this component is essentially useless for the most basic use case for a date....Birthday.
> 
> By not allowing the user to select a year, they have to scroll through 20 years of months to select a date in the past. 🤦

🤣 so sorry the component I've shared doesn't exactly meet your requirements.

A year picker has been added to the recently released v3 of this component.  It's pretty neat.. uses a virtual list/grid and has scroll, keyboard, and touch support (as do the day and month pickers).   You can see this [in the demo](https://6edesign.github.io/svelte-calendar).

**Pull request closed without merging**
